--creacion de tablas
--RAMA ESQUEMA_OFICIAL_AVH
--COMMIT 'PRACTICA DEL HOSPITAL'
CREATE TABLE PERSONAL(
PERSONA_ID NUMBER(11) PRIMARY KEY,
NOMBRE NVARCHAR2(20),
FECHA_NAC DATE,
CARGO NVARCHAR2(30),
DEPARTAMENTO_ID NUMBER(11)
);

CREATE TABLE DOCTORES(
DOCTOR_ID NUMBER(11) PRIMARY KEY,
NOMBRE NVARCHAR2(15),
ESPECIALIDAD NVARCHAR2(15),
CEDULA NVARCHAR2(15),
FECHA_NAC DATE,
SEXO NVARCHAR2(1)
);

CREATE TABLE DEPARTAMENTOS(
DEPARTAMENTO_ID NUMBER(11) PRIMARY KEY,
DESCRIPCION NVARCHAR2(30),
N_PERSONAL NUMBER(11),
DOCTOR_ID NUMBER(11)
);

CREATE TABLE DIAGNOSTICO(
DIAGNOSTICO_ID NUMBER(11) PRIMARY KEY,
FECHA DATE,
DETALLE NVARCHAR2(100),
DOCTOR_ID NUMBER(11),
PACIENTE_ID NUMBER(11)
);

CREATE TABLE CITAS_PROGRAMADAS(
CITA_ID NUMBER(11) PRIMARY KEY,
FECHA_CITA DATE,
STATUS CHAR(1),
PESO NUMBER(11),
ESTATURA NUMBER(11),
PACIENTE_ID NUMBER(11),
DEPARTAMENTO_ID NUMBER(11)
);

CREATE TABLE PACIENTES(
PACIENTE_ID NUMBER(11) PRIMARY KEY,
NOMBRE NVARCHAR2(15),
APELLIDO_P NVARCHAR2(15),
APM NVARCHAR2(15),
CURP NVARCHAR2(20),
FECHA_NAC DATE,
NSS NVARCHAR2(10),
SEXO NVARCHAR2(1),
TIPO_SANGRE NVARCHAR2(3)
);

CREATE TABLE RECETA(
RECETA_ID NUMBER(11) PRIMARY KEY,
STATUS NVARCHAR2(10),
DIAGNOSTICO_ID NUMBER(11)
);

CREATE TABLE DETALLES_RECETA(
DET_REC_ID NUMBER(11) PRIMARY KEY,
DOSIS NVARCHAR2(50),
RECETA_ID NUMBER(11),
MEDICAMENTO_ID NUMBER(11)
);

CREATE TABLE MEDICAMENTOS(
MEDICAMENTO_ID NUMBER(11) PRIMARY KEY,
NOMBRE NVARCHAR2(20),
PATENTE CHAR(1),
FECHA_CAD DATE,
INGREDIENTE_ACT NVARCHAR2(25),
MARCA NVARCHAR2(15)
);

ALTER TABLE PERSONAL ADD CONSTRAINT FK_PERSONAL_DEPARTAMENTO_ID
FOREIGN KEY (DEPARTAMENTO_ID)
REFERENCES DEPARTAMENTOS(DEPARTAMENTO_ID);

ALTER TABLE DEPARTAMENTOS ADD CONSTRAINT FK_DEPARTAMENTO_DOCTOR_ID
FOREIGN KEY (DOCTOR_ID)
REFERENCES DOCTORES(DOCTOR_ID);

ALTER TABLE DIAGNOSTICO ADD CONSTRAINT FK_DIAGNOSTICO_DOCTOR_ID
FOREIGN KEY (DOCTOR_ID)
REFERENCES DOCTORES(DOCTOR_ID);

ALTER TABLE DIAGNOSTICO ADD CONSTRAINT FK_DIAGNOSTICO_PACIENTE_ID
FOREIGN KEY (PACIENTE_ID)
REFERENCES PACIENTES(PACIENTE_ID);

ALTER TABLE CITAS_PROGRAMADAS ADD CONSTRAINT FK_CPROGRAMADAS_PACIENTE_ID
FOREIGN KEY (PACIENTE_ID)
REFERENCES PACIENTES(PACIENTE_ID);

ALTER TABLE CITAS_PROGRAMADAS ADD CONSTRAINT FK_CPROGRAMADAS_DEPARTA_ID
FOREIGN KEY(DEPARTAMENTO_ID)
REFERENCES DEPARTAMENTOS(DEPARTAMENTO_ID);

ALTER TABLE RECETA ADD CONSTRAINT FK_RECETA_DIAGNOSTICO_ID
FOREIGN KEY(DIAGNOSTICO_ID)
REFERENCES DIAGNOSTICO(DIAGNOSTICO_ID);

ALTER TABLE DETALLES_RECETA ADD CONSTRAINT FK_DETAL_RECETA_RECETA_ID
FOREIGN KEY (RECETA_ID)
REFERENCES RECETA(RECETA_ID);

ALTER TABLE DETALLES_RECETA ADD CONSTRAINT FK_DETAL_RECETA_MEDICAMENTO_ID
FOREIGN KEY (MEDICAMENTO_ID)
REFERENCES MEDICAMENTOS(MEDICAMENTO_ID);
--------------------------------------------------------------------------------
--AUTOMATIZACION DE ID'S CON SEQUENCES AND TRIGGERS
--TABLA DOCTORES
CREATE SEQUENCE DOCTORES_SQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER ON_INSERT_DOCTORES BEFORE
INSERT ON DOCTORES FOR EACH ROW BEGIN
SELECT DOCTORES_SQ.NEXTVAL INTO:new.DOCTOR_ID FROM dual;
END;

INSERT ALL
INTO DOCTORES(NOMBRE,ESPECIALIDAD,CEDULA,FECHA_NAC,SEXO)VALUES('ALDO','ESPECIALIDAD 1','XXXX','28-07-2000','M')
INTO DOCTORES(NOMBRE,ESPECIALIDAD,CEDULA,FECHA_NAC,SEXO)VALUES('ANA','ESPECIALIDAD 2','XXXX','01-01-2001','F')
INTO DOCTORES(NOMBRE,ESPECIALIDAD,CEDULA,FECHA_NAC,SEXO)VALUES('LUIS','ESPECIALIDAD 3','XXXX','18-06-1999','M')
INTO DOCTORES(NOMBRE,ESPECIALIDAD,CEDULA,FECHA_NAC,SEXO)VALUES('EDITH','ESPECIALIDAD 4','XXXX','02-11-2002','F')
SELECT *FROM dual;

SELECT *FROM DOCTORES;
---------------------------------------------------------------------------------------------------------------------
--TABLA DEPARTAMENTO
CREATE SEQUENCE DEPARTAMENTOS_SQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER ON_INSERT_DEPARTAMENTO BEFORE
INSERT ON DEPARTAMENTOS FOR EACH ROW BEGIN
SELECT DEPARTAMENTOS_SQ.NEXTVAL INTO:new.DEPARTAMENTO_ID FROM dual;
END;

INSERT ALL
INTO DEPARTAMENTOS(DESCRIPCION,N_PERSONAL,DOCTOR_ID)VALUES('DESCRIPCION X','987',1)
INTO DEPARTAMENTOS(DESCRIPCION,N_PERSONAL,DOCTOR_ID)VALUES('DESCRIPCION X','5432',3)
INTO DEPARTAMENTOS(DESCRIPCION,N_PERSONAL,DOCTOR_ID)VALUES('DESCRIPCION X','8786',4)
INTO DEPARTAMENTOS(DESCRIPCION,N_PERSONAL,DOCTOR_ID)VALUES('DESCRIPCION X','7653',2)
SELECT *FROM dual;

SELECT *FROM DEPARTAMENTOS;
-----------------------------------------------------------------------------------------------
--TABLA PERSONAL
CREATE SEQUENCE PERSONAL_SQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER ON_INSERT_PERSONAL BEFORE
INSERT ON PERSONAL FOR EACH ROW BEGIN
SELECT PERSONAL_SQ.NEXTVAL INTO:new.PERSONAL_ID FROM dual;
END;

INSERT ALL
INTO PERSONAL(NOMBRE,FECHA_NAC,CARGO,DEPARTAMENTO_ID)VALUES('HUGO','09-02-1997','CARGO X',2)
INTO PERSONAL(NOMBRE,FECHA_NAC,CARGO,DEPARTAMENTO_ID)VALUES('MARCO','11-04-1992','CARGO X',1)
INTO PERSONAL(NOMBRE,FECHA_NAC,CARGO,DEPARTAMENTO_ID)VALUES('MARIA','01-09-1998','CARGO X',4)
INTO PERSONAL(NOMBRE,FECHA_NAC,CARGO,DEPARTAMENTO_ID)VALUES('JULIA','23-11-1995','CARGO X',3)
SELECT *FROM dual;

SELECT *FROM PERSONAL;
----------------------------------------------------------------------------------------------
--TABLA PACIENTES
CREATE SEQUENCE PACIENTES_SQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER ON_INSERT_PACIENTE BEFORE
INSERT ON PACIENTES FOR EACH ROW BEGIN
SELECT PACIENTES_SQ.NEXTVAL INTO:new.PACIENTE_ID FROM dual;
END;

INSERT ALL
INTO PACIENTES(NOMBRE,APELLIDO_P,APM,CURP,FECHA_NAC,NSS,SEXO,TIPO_SANGRE)
VALUES('RAUL','JIMENEZ','TORRES','XXXXXXX','12-01-1990','GR-65','M','O+')
INTO PACIENTES(NOMBRE,APELLIDO_P,APM,CURP,FECHA_NAC,NSS,SEXO,TIPO_SANGRE)
VALUES('JESUS','HERNANDEZ','SERON','XXXXXXX','01-11-1991','GR-65','M','O-')
INTO PACIENTES(NOMBRE,APELLIDO_P,APM,CURP,FECHA_NAC,NSS,SEXO,TIPO_SANGRE)
VALUES('MARTIN','CORDOVA','VALADEZ','XXXXXXX','23-12-1989','GR-65','M','O+')
INTO PACIENTES(NOMBRE,APELLIDO_P,APM,CURP,FECHA_NAC,NSS,SEXO,TIPO_SANGRE)
VALUES('AQUILES','MORAN','CORDOVA','XXXXXXX','25-05-1988','GR-65','M','O-')
INTO PACIENTES(NOMBRE,APELLIDO_P,APM,CURP,FECHA_NAC,NSS,SEXO,TIPO_SANGRE)
VALUES('LENIN','MUÑOS','GARCIA','XXXXXXX','18-03-1970','GR-65','M','O+')
SELECT *FROM dual;

SELECT *FROM PACIENTES;
------------------------------------------------------------------------------------
--TABLA CITAS_PROGRAMADAS
CREATE SEQUENCE CITAS_PROGRAMADAS_SQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER ON_INSERT_CPROGRAMADAS BEFORE
INSERT ON CITAS_PROGRAMADAS FOR EACH ROW BEGIN
SELECT CITAS_PROGRAMADAS_SQ.NEXTVAL INTO:new.CITA_ID FROM dual;
END;

INSERT ALL
INTO CITAS_PROGRAMADAS(FECHA_CITA,STATUS,PESO,ESTATURA,PACIENTE_ID,DEPARTAMENTO_ID)
VALUES('12-10-2023','P',62,1.75,5,4)
INTO CITAS_PROGRAMADAS(FECHA_CITA,STATUS,PESO,ESTATURA,PACIENTE_ID,DEPARTAMENTO_ID)
VALUES('12-01-2023','R',53,1.60,4,3)
INTO CITAS_PROGRAMADAS(FECHA_CITA,STATUS,PESO,ESTATURA,PACIENTE_ID,DEPARTAMENTO_ID)
VALUES('23-11-2023','P',67,1.61,3,2)
INTO CITAS_PROGRAMADAS(FECHA_CITA,STATUS,PESO,ESTATURA,PACIENTE_ID,DEPARTAMENTO_ID)
VALUES('01-02-2023','R',60,1.71,1,4)
INTO CITAS_PROGRAMADAS(FECHA_CITA,STATUS,PESO,ESTATURA,PACIENTE_ID,DEPARTAMENTO_ID)
VALUES('19-12-2023','P',58,1.73,2,1)
SELECT *FROM dual;

SELECT *FROM CITAS_PROGRAMADAS;
-------------------------------------------------------------------------------------------
--TABLA DIAGNOSTICO
CREATE SEQUENCE DIAGNOSTICO_SQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER ON_INSERT_DIAGNOSTICO BEFORE
INSERT ON DIAGNOSTICO FOR EACH ROW BEGIN
SELECT DIAGNOSTICO_SQ.NEXTVAL INTO:new.DIAGNOSTICO_ID FROM dual;
END;

INSERT ALL
INTO DIAGNOSTICO(FECHA,DETALLE,DOCTOR_ID,PACIENTE_ID)
VALUES('12-04-2023','DETALLE XX',3,2)
INTO DIAGNOSTICO(FECHA,DETALLE,DOCTOR_ID,PACIENTE_ID)
VALUES('02-05-2023','DETALLE XX',4,4)
INTO DIAGNOSTICO(FECHA,DETALLE,DOCTOR_ID,PACIENTE_ID)
VALUES('05-05-2023','DETALLE XX',1,3)
INTO DIAGNOSTICO(FECHA,DETALLE,DOCTOR_ID,PACIENTE_ID)
VALUES('07-04-2023','DETALLE XX',2,1)
INTO DIAGNOSTICO(FECHA,DETALLE,DOCTOR_ID,PACIENTE_ID)
VALUES('10-05-2023','DETALLE XX',2,5)
SELECT *FROM dual;

SELECT *FROM DIAGNOSTICO;
---------------------------------------------------------------------------------------
--TABLA RECETA
CREATE SEQUENCE RECETA_SQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER ON_INSERT_RECETA BEFORE
INSERT ON RECETA FOR EACH ROW BEGIN
SELECT RECETA_SQ.NEXTVAL INTO:new.RECETA_ID FROM dual;
END;

INSERT ALL
INTO RECETA(STATUS,DIAGNOSTICO_ID)VALUES('APROBADA',3)
INTO RECETA(STATUS,DIAGNOSTICO_ID)VALUES('NOAPROBA',4)
INTO RECETA(STATUS,DIAGNOSTICO_ID)VALUES('APROBADA',5)
INTO RECETA(STATUS,DIAGNOSTICO_ID)VALUES('NOAPROBA',1)
INTO RECETA(STATUS,DIAGNOSTICO_ID)VALUES('APROBADA',2)
SELECT *FROM dual;

SELECT *FROM RECETA;
---------------------------------------------------------------------------------------
--TABLA MEDICAMENTO
CREATE SEQUENCE MEDICAMENTO_SQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER ON_INSERT_MEDICAMENTO BEFORE
INSERT ON MEDICAMENTOS FOR EACH ROW BEGIN
SELECT MEDICAMENTO_SQ.NEXTVAL INTO:new.MEDICAMENTO_ID FROM dual;
END;

INSERT ALL
INTO MEDICAMENTOS(NOMBRE,PATENTE,FECHA_CAD,INGREDIENTE_ACT,MARCA)
VALUES('PARACETAMOL', 'M', '02-02-2025','INCREDIENTE X','MARCA X')
INTO MEDICAMENTOS(NOMBRE,PATENTE,FECHA_CAD,INGREDIENTE_ACT,MARCA)
VALUES('ASPIRINA', 'L', '02-02-2027','INCREDIENTE X','MARCA X')
INTO MEDICAMENTOS(NOMBRE,PATENTE,FECHA_CAD,INGREDIENTE_ACT,MARCA)
VALUES('DETOROLACO', 'M', '02-02-2026','INCREDIENTE X','MARCA X')
INTO MEDICAMENTOS(NOMBRE,PATENTE,FECHA_CAD,INGREDIENTE_ACT,MARCA)
VALUES('ANTIBIOTICO', 'L', '02-02-2028','INCREDIENTE X','MARCA X')
INTO MEDICAMENTOS(NOMBRE,PATENTE,FECHA_CAD,INGREDIENTE_ACT,MARCA)
VALUES('MEDICAMENTO X', 'M', '02-02-2030','INCREDIENTE X','MARCA X')
SELECT *FROM dual;

SELECT *FROM MEDICAMENTOS;
---------------------------------------------------------------------------------
--TABLA DETALLE_RECETA

CREATE SEQUENCE DETALLE_RECETA_SQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER ON_INSERT_DRECETA BEFORE
INSERT ON DETALLES_RECETA FOR EACH ROW BEGIN
SELECT DETALLE_RECETA_SQ.NEXTVAL INTO:new.DET_REC_ID FROM dual;
END;

INSERT ALL
INTO DETALLES_RECETA(DOSIS,RECETA_ID,MEDICAMENTO_ID)VALUES('DOSIS XYYTQ',3,1)
INTO DETALLES_RECETA(DOSIS,RECETA_ID,MEDICAMENTO_ID)VALUES('DOSIS XYYTQ',4,2)
INTO DETALLES_RECETA(DOSIS,RECETA_ID,MEDICAMENTO_ID)VALUES('DOSIS XYYTQ',5,5)
INTO DETALLES_RECETA(DOSIS,RECETA_ID,MEDICAMENTO_ID)VALUES('DOSIS XYYTQ',6,4)
INTO DETALLES_RECETA(DOSIS,RECETA_ID,MEDICAMENTO_ID)VALUES('DOSIS XYYTQ',7,3)
SELECT *FROM dual;

SELECT *FROM DETALLES_RECETA;