CREATE TABLE PERSONAL(
PERSONAL_ID INT  PRIMARY KEY,
NOMBRE NVARCHAR2(50),
FECHA_NAC DATE,
CARGO NVARCHAR2(20),
);
ALTER TABLE PERSONAL ADD DEPARTAMENTO_ID INT
ALTER TABLE PERSONAL ADD CONSTRAINT FK_PERSONAL_DEPARTAMENTO_ID
FOREIGN KEY (DEPARTAMENTO_ID)
REFERENCES DEPARTAMENTO(DEPARTAMENTO_ID);

CREATE TABLE DEPARTAMENTO(
DEPARTAMENTO_ID INT PRIMARY KEY,
DESCRIPCION NVARCHAR2(50),
N_PERSONA INT,

);
ALTER TABLE DEPARTAMENTO ADD DOCTOR_ID INT
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT FK_DEPARTAMENTO_DOCTOR_ID
FOREIGN KEY (DOCTOR_ID)
REFERENCES DOCTORES(DOCTOR_ID);


CREATE TABLE CITAS_PROGRAMADAS(
CITA_ID INT PRIMARY KEY,
FECHA_CITA DATE,
STATUS NVARCHAR2 (1),
PESO INT,
ESTATURA INT
);
ALTER TABLE CITAS_PROGRAMADAS ADD PACIENTE_ID INT
ALTER TABLE CITAS_PROGRAMADAS ADD DEPARTAMENTO_ID INT

ALTER TABLE CITAS_PROGRAMADAS ADD CONSTRAINT FK_CITAS_PROG_PACIENTE_ID
FOREIGN KEY (PACIENTE_ID)
REFERENCES PACIENTES(PACIENTE_ID);

ALTER TABLE CITAS_PROGRAMADAS ADD CONSTRAINT FK_CITAS_PROG_DEP_ID
FOREIGN KEY (DEPARTAMENTO_ID)
REFERENCES DEPARTAMENTO(DEPARTAMENTO_ID);

CREATE TABLE PACIENTES(
PACIENTE_ID INT PRIMARY KEY,
NOMBRE NVARCHAR2 (15),
APP NVARCHAR2(15),
APM NVARCHAR2(15),
CURP NVARCHAR2(20),
FECHA_NAC DATE,
NSS NVARCHAR2(10),
SEXO NVARCHAR2(12),
TIPO_SANGRE NVARCHAR2(12)
);

CREATE TABLE DIAGNOSTICO(
DIAGNOSTICO_ID INT PRIMARY KEY,
FECHA DATE,
DETALLE NVARCHAR2(20)
);
ALTER TABLE DIAGNOSTICO ADD DOCTOR_ID INT
ALTER TABLE DIAGNOSTICO ADD CONSTRAINT FK_DIAG_DOCTOR_ID
FOREIGN KEY (DOCTOR_ID)
REFERENCES DOCTORES(DOCTOR_ID);

CREATE TABLE RECETA(
RECETA_ID INT PRIMARY KEY,
STATUS NVARCHAR2(10)
);
ALTER TABLE RECETA ADD DIAGNOSTICO_ID INT
ALTER TABLE RECETA ADD CONSTRAINT FK_REC_DIAG_ID
FOREIGN KEY (DIAGNOSTICO_ID)
REFERENCES DIAGNOSTICO(DIAGNOSTICO_ID);

CREATE TABLE DETALLES_RECETA(
DET_REC_ID INT PRIMARY KEY,
DOSIS NVARCHAR2(50)
);
ALTER TABLE DETALLES_RECETA ADD RECETA_ID INT
ALTER TABLE DETALLES_RECETA ADD CONSTRAINT FK_DET_REC_REC_ID
FOREIGN KEY (RECETA_ID)
REFERENCES RECETA(RECETA_ID);

CREATE TABLE MEDICAMENTOS(
MEDICAMENTOS_ID INT PRIMARY KEY,
NOMBRE NVARCHAR2(20),
PATENTE NVARCHAR2(1),
FECHA_CAD DATE,
INGREDIENTE_ACT NVARCHAR2(25),
MARCA NVARCHAR2(15)
);

CREATE TABLE DOCTORES(
DOCTOR_ID INT PRIMARY KEY,
NOMBRE NVARCHAR2(15),
ESPECIALIDAD NVARCHAR2(15),
CEDULA NVARCHAR2(15),
FECHA_NAC DATE,
SEXO NVARCHAR2(1)
);
CREATE SEQUENCE PERSONAL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DEP_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CIT_PROG_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PACIENTES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DIAGNOSTICO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RECETA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DET_REC_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MEDICAMENTOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DOCTORES_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER ON_INSERT_PERSONAL BEFORE
INSERT ON PERSONAL FOR EACH ROW BEGIN
SELECT PERSONAL_SEQ.NEXTVAL INTO :new.PERSONAL_ID FROM duaL;
END;
INSERT ALL
INTO PERSONAL(NOMBRE,FECHA_NAC,CARGO)VALUES('PEDRO','02-12-2022','LIMPIEZA')
INTO PERSONAL(NOMBRE,FECHA_NAC,CARGO)VALUES('MARIO','03-12-2023','ENFERMERO')
INTO PERSONAL(NOMBRE,FECHA_NAC,CARGO)VALUES('JOSE','04-12-2023','SECRETARIO')
INTO PERSONAL(NOMBRE,FECHA_NAC,CARGO)VALUES('RAUL','05-12-2023','ADMINISTRADOR')
SELECT * FROM DUAL;

CREATE OR REPLACE TRIGGER ON_INSERT_DEPTO BEFORE
INSERT ON DEPARTAMENTO FOR EACH ROW BEGIN
SELECT DEP_SEQ.NEXTVAL INTO :new.DEPARTAMENTO_ID FROM duaL;
END;
INSERT ALL
INTO DEPARTAMENTO(DESCRIPCION,N_PERSONA)VALUES('VERDE','02')
INTO DEPARTAMENTO(DESCRIPCION,N_PERSONA)VALUES('AMARILLO','03')
INTO DEPARTAMENTO(DESCRIPCION,N_PERSONA)VALUES('AZUL','04')
INTO DEPARTAMENTO(DESCRIPCION,N_PERSONA)VALUES('BLANCO','05')
SELECT * FROM DUAL;

CREATE OR REPLACE TRIGGER ON_INSERT_CIT_PROG BEFORE
INSERT ON CITAS_PROGRAMADAS FOR EACH ROW BEGIN
SELECT CIT_PROG_SEQ.NEXTVAL INTO :new.CITA_ID FROM duaL;
END;

INSERT ALL
INTO CITAS_PROGRAMADAS(FECHA_CITA,STATUS,PESO,ESTATURA)VALUES('02-03-2023','S','75','176 ')
INTO CITAS_PROGRAMADAS(FECHA_CITA,STATUS,PESO,ESTATURA)VALUES('03-03-2023','S','76','177 ')
INTO CITAS_PROGRAMADAS(FECHA_CITA,STATUS,PESO,ESTATURA)VALUES('04-03-2023','S','77','178 ')
INTO CITAS_PROGRAMADAS(FECHA_CITA,STATUS,PESO,ESTATURA)VALUES('05-03-2023','S','78','179 ')
SELECT * FROM DUAL;

CREATE OR REPLACE TRIGGER ON_INSERT_PACIENTES BEFORE
INSERT ON PACIENTES FOR EACH ROW BEGIN
SELECT PACIENTES_SEQ.NEXTVAL INTO :new.PACIENTE_ID FROM duaL;
END;

INSERT ALL
INTO PACIENTES(NOMBRE,APP,APM,CURP,FECHA_NAC,NSS,SEXO,TIPO_SANGRE)VALUES('PEDRO','FNFU','FIJIFJIF','FIYFFI','09-01-2023','BDRYDYD','MASCULLINO','O+')
INTO PACIENTES(NOMBRE,APP,APM,CURP,FECHA_NAC,NSS,SEXO,TIPO_SANGRE)VALUES('LIZ','FNFRU','FIJFYJIF','FIFGFI','10-01-2023','BDYTDYD','FEMENINO','A+')
INTO PACIENTES(NOMBRE,APP,APM,CURP,FECHA_NAC,NSS,SEXO,TIPO_SANGRE)VALUES('MARIO','DFNFU','FIJFJIFT','BFIFFI','11-01-2023','TBDYDYD','MASCULLINO','O+')
INTO PACIENTES(NOMBRE,APP,APM,CURP,FECHA_NAC,NSS,SEXO,TIPO_SANGRE)VALUES('JOSE','FANFU','FIJFRJIF','FBIFFI','12-01-2023','BYDYDYD','MASCULLINO','O+')
SELECT * FROM DUAL;

CREATE OR REPLACE TRIGGER ON_INSERT_DIAGNOSTICO BEFORE
INSERT ON DIAGNOSTICO FOR EACH ROW BEGIN
SELECT DIAGNOSTICO_SEQ.NEXTVAL INTO :new.DIAGNOSTICO_ID FROM duaL;
END;
INSERT ALL
INTO DIAGNOSTICO(FECHA,DETALLE)VALUES('09-01-2023','BDRYEDYD')
INTO DIAGNOSTICO(FECHA,DETALLE)VALUES('10-01-2023','BDRRYDYD')
INTO DIAGNOSTICO(FECHA,DETALLE)VALUES('11-01-2023','BTDRYDYD')
INTO DIAGNOSTICO(FECHA,DETALLE)VALUES('12-01-2023','YBDRYDYD')
SELECT * FROM DUAL;

CREATE OR REPLACE TRIGGER ON_INSERT_RECETA BEFORE
INSERT ON RECETA FOR EACH ROW BEGIN
SELECT RECETA_SEQ.NEXTVAL INTO :new.RECETA_ID FROM duaL;
END;
INSERT ALL
INTO RECETA(STATUS)VALUES('OK')
INTO RECETA(STATUS)VALUES('NO')
INTO RECETA(STATUS)VALUES('OK')
INTO RECETA(STATUS)VALUES('NO')
SELECT * FROM DUAL;

CREATE OR REPLACE TRIGGER ON_INSERT_DET_RECETA BEFORE
INSERT ON DETALLES_RECETA FOR EACH ROW BEGIN
SELECT DET_REC_SEQ.NEXTVAL INTO :new.DET_REC_ID FROM duaL;
END;
INSERT ALL
INTO DETALLES_RECETA(DOSIS)VALUES('100 GR')
INTO DETALLES_RECETA(DOSIS)VALUES('120 GR')
INTO DETALLES_RECETA(DOSIS)VALUES('23 GR')
INTO DETALLES_RECETA(DOSIS)VALUES('40 GR')
SELECT * FROM DUAL;

CREATE OR REPLACE TRIGGER ON_INSERT_MEDICAMENTOS BEFORE
INSERT ON MEDICAMENTOS FOR EACH ROW BEGIN
SELECT MEDICAMENTOS_SEQ.NEXTVAL INTO :new.MEDICAMENTOS_ID FROM duaL;
END;

INSERT ALL
INTO MEDICAMENTOS(NOMBRE,PATENTE,FECHA_CAD,INGREDIENTE_ACT,MARCA)VALUES('PEDRO','S','02-02-2023','NUFFUU','YDNUU')
INTO MEDICAMENTOS(NOMBRE,PATENTE,FECHA_CAD,INGREDIENTE_ACT,MARCA)VALUES('JOSE','S','03-02-2023','NUFYFU','DGNUU')
INTO MEDICAMENTOS(NOMBRE,PATENTE,FECHA_CAD,INGREDIENTE_ACT,MARCA)VALUES('LUIS','S','04-02-2023','NUTFFU','DNFUU')
INTO MEDICAMENTOS(NOMBRE,PATENTE,FECHA_CAD,INGREDIENTE_ACT,MARCA)VALUES('MARIO','S','05-02-2023','NRUFFU','DNUDU')
SELECT * FROM DUAL;

CREATE OR REPLACE TRIGGER ON_INSERT_DOCTORES BEFORE
INSERT ON DOCTORES FOR EACH ROW BEGIN
SELECT DOCTORES_SEQ.NEXTVAL INTO :new.DOCTOR_ID FROM duaL;
END;
INSERT ALL
INTO DOCTORES(NOMBRE,ESPECIALIDAD,CEDULA,FECHA_NAC,SEXO)VALUES('PEDRO','DIJD','HDYHDYHD','03-02-1980','M')
INTO DOCTORES(NOMBRE,ESPECIALIDAD,CEDULA,FECHA_NAC,SEXO)VALUES('JOSE','DEED','FFHF','03-02-2023','M')
INTO DOCTORES(NOMBRE,ESPECIALIDAD,CEDULA,FECHA_NAC,SEXO)VALUES('LUIS','FRS','FFJFIF','04-02-2023','M')
INTO DOCTORES(NOMBRE,ESPECIALIDAD,CEDULA,FECHA_NAC,SEXO)VALUES('MARIO','GSR','FJFIFI','05-02-2023','M')
SELECT * FROM DUAL;





