CREATE TABLE DOCTORES(
DOCTOR_ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(15),
ESPECIALIDAD NVARCHAR2(15),
CEDULA NVARCHAR2(15),
FECHA_NAC DATE,
SEXO NVARCHAR2(1)
);

CREATE TABLE MEDICAMENTOS(
MEDICAMENTO_ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(20),
PATENTE NVARCHAR2(1),
FECHA_CAD DATE,
INGREDIENTE_ACT NVARCHAR2(25),
MARCA NVARCHAR2(15)
);

CREATE TABLE PACIENTES(
PACIENTE_ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(15),
APLL_PA NVARCHAR2(15),
APLL_MA NVARCHAR2(15),
CURP NVARCHAR2(20),
FECHA_NAC DATE,
NSS NVARCHAR2(10),
SEXO NVARCHAR2(1),
TIPO_SANGRE NVARCHAR2(3)
);

CREATE TABLE PERSONAL(
PERSONAL_ID NUMBER PRIMARY KEY,
DEPARTAMENTO_ID NUMBER,
NOMBRE NVARCHAR2(20),
FECHA_NAC DATE,
CARGO NVARCHAR2(30)
);

CREATE TABLE DEPARTAMENTOS(
DEPARTAMENTO_ID NUMBER PRIMARY KEY,
DOCTOR_ID NUMBER,
DESCRIPCION NVARCHAR2(30),
N_PERSONAL NUMBER(11)
);

CREATE TABLE CITAS_PROGRAMADAS(
CITA_ID NUMBER PRIMARY KEY,
PACIENTE_ID NUMBER,
DEPARTAMENTO_ID NUMBER,
FECHA_CITA DATE,
STATUS CHAR(1),
PESO NUMBER(11),
ALTURA NUMBER(11)
);

CREATE TABLE DIAGNOSTICO(
DIAGNOSTICO_ID NUMBER PRIMARY KEY,
DOCTOR_ID NUMBER,
PACIENTE_ID NUMBER,
FECHA DATE,
DETALLE NVARCHAR2(100)
);

CREATE TABLE RECETA(
RECETA_ID NUMBER PRIMARY KEY,
DIAGNOSTICO_ID NUMBER,
STATUS NVARCHAR2(10)
);

CREATE TABLE DETALLES_RECETA(
DET_REC_ID NUMBER PRIMARY KEY,
RECETA_ID NUMBER,
MEDICAMENTO_ID NUMBER,
DOSIS NVARCHAR2(50)
);

-- SECUENCIAS
CREATE SEQUENCE DOCTORES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MEDICAMENTOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PERSONAL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DEPARTAMENTOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CITAS_PROGRAMADAS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DIAGNOSTICO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RECETA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PACIENTES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DETALLES_RECETA_SEQ START WITH 1 INCREMENT BY 1;

--TRIGGERS
CREATE OR REPLACE TRIGGER ON_INSERT_DOCTORES BEFORE
INSERT ON DOCTORES FOR EACH ROW BEGIN
SELECT DOCTORES_SEQ.NEXTVAL INTO :new.DOCTOR_ID from dual;
END;

CREATE OR REPLACE TRIGGER ON_INSERT_PERSONAL BEFORE
INSERT ON PERSONAL FOR EACH ROW BEGIN
SELECT PERSONAL_SEQ.NEXTVAL INTO :new.PERSONAL_ID from dual;
END;

CREATE OR REPLACE TRIGGER ON_INSERT_DEPARTAMENTOS BEFORE
INSERT ON DEPARTAMENTOS FOR EACH ROW BEGIN
SELECT DEPARTAMENTOS_SEQ.NEXTVAL INTO :new.DEPARTAMENTO_ID from dual;
END;

CREATE OR REPLACE TRIGGER ON_INSERT_CITAS_PROGRAMADAS BEFORE
INSERT ON CITAS_PROGRAMADAS FOR EACH ROW BEGIN
SELECT CITAS_PROGRAMADAS_SEQ.NEXTVAL INTO :new.CITA_ID from dual;
END;

CREATE OR REPLACE TRIGGER ON_INSERT_DIAGNOSTICO BEFORE
INSERT ON DIAGNOSTICO FOR EACH ROW BEGIN
SELECT DIAGNOSTICO_SEQ.NEXTVAL INTO :new.DIAGNOSTICO_ID from dual;
END;

CREATE OR REPLACE TRIGGER ON_INSERT_RECETA BEFORE
INSERT ON RECETA FOR EACH ROW BEGIN
SELECT RECETA_SEQ.NEXTVAL INTO :new.RECETA_ID from dual;
END;

CREATE OR REPLACE TRIGGER ON_INSERT_PACIENTES BEFORE
INSERT ON PACIENTES FOR EACH ROW BEGIN
SELECT PACIENTES_SEQ.NEXTVAL INTO :new.PACIENTE_ID from dual;
END;

CREATE OR REPLACE TRIGGER ON_INSERT_DETALLES_RECETA BEFORE
INSERT ON DETALLES_RECETA FOR EACH ROW BEGIN
SELECT DETALLES_RECETA_SEQ.NEXTVAL INTO :new.DET_REC_ID from dual;
END;

CREATE OR REPLACE TRIGGER ON_INSERT_MEDICAMENTOS BEFORE
INSERT ON MEDICAMENTOS FOR EACH ROW BEGIN
SELECT MEDICAMENTOS_SEQ.NEXTVAL INTO :new.MEDICAMENTO_ID from dual;
END;

--LLAVES FORANEAS
ALTER TABLE PERSONAL
ADD CONSTRAINT PERSONAL_DEPARTAMENTOS_FK FOREIGN KEY (DEPARTAMENTO_ID)
REFERENCES DEPARTAMENTOS (DEPARTAMENTO_ID);

ALTER TABLE DEPARTAMENTOS
ADD CONSTRAINT DEPARTAMENTOS_DOCTORES_FK FOREIGN KEY (DOCTOR_ID)
REFERENCES DOCTORES (DOCTOR_ID);

ALTER TABLE CITAS_PROGRAMADAS
ADD CONSTRAINT CITAS_DEPARTAMENTOS_FK FOREIGN KEY (DEPARTAMENTO_ID)
REFERENCES DEPARTAMENTOS (DEPARTAMENTO_ID);

ALTER TABLE CITAS_PROGRAMADAS
ADD CONSTRAINT CITAS_PACIENTES_FK FOREIGN KEY (PACIENTE_ID)
REFERENCES PACIENTES (PACIENTE_ID);

ALTER TABLE DIAGNOSTICO
ADD CONSTRAINT DIAGNOSTICO_DOCTOR_FK FOREIGN KEY (DOCTOR_ID)
REFERENCES DOCTORES (DOCTOR_ID);

ALTER TABLE DIAGNOSTICO
ADD CONSTRAINT DIAGNOSTICO_PACIENTE_FK FOREIGN KEY (PACIENTE_ID)
REFERENCES PACIENTES (PACIENTE_ID);

ALTER TABLE RECETA
ADD CONSTRAINT RECETA_DIAGNOSTICO_FK FOREIGN KEY (DIAGNOSTICO_ID)
REFERENCES DIAGNOSTICO (DIAGNOSTICO_ID);

ALTER TABLE DETALLES_RECETA
ADD CONSTRAINT DR_RECETA_FK FOREIGN KEY (RECETA_ID)
REFERENCES RECETA (RECETA_ID);

ALTER TABLE DETALLES_RECETA
ADD CONSTRAINT DR_MEDICAMENTOS_FK FOREIGN KEY (MEDICAMENTO_ID)
REFERENCES MEDICAMENTOS (MEDICAMENTO_ID);

--INSERCION DE DATOS

INSERT ALL
INTO DOCTORES(NOMBRE,ESPECIALIDAD,CEDULA,FECHA_NAC,SEXO)VALUES('ALFONSO','CIRUJANO','3625477899','15-02-1990','M')
INTO DOCTORES(NOMBRE,ESPECIALIDAD,CEDULA,FECHA_NAC,SEXO)VALUES('KAREN','PEDIATRA','6345824595','30-06-1985','F')
INTO DOCTORES(NOMBRE,ESPECIALIDAD,CEDULA,FECHA_NAC,SEXO)VALUES('EDUARDO','PSICOLOGIA','2154856325','27-02-1991','M')
INTO DOCTORES(NOMBRE,ESPECIALIDAD,CEDULA,FECHA_NAC,SEXO)VALUES('ALAN','CARDIOLOGO','3695862416','12-11-1989','M')
INTO DOCTORES(NOMBRE,ESPECIALIDAD,CEDULA,FECHA_NAC,SEXO)VALUES('LAURA','DERMATOLOGA','4612358753','20-04-1992','F')
SELECT * FROM DUAL;
SELECT * FROM DOCTORES;

INSERT ALL
INTO MEDICAMENTOS(NOMBRE,PATENTE,FECHA_CAD,INGREDIENTE_ACT,MARCA)VALUES('ASPIRINA','1','15-06-2025','ACIDO ACETILSALICILICO','BAYER')
INTO MEDICAMENTOS(NOMBRE,PATENTE,FECHA_CAD,INGREDIENTE_ACT,MARCA)VALUES('OMEPRAZOL','2','30-09-2023','AMEPRAMIL','BAYER')
INTO MEDICAMENTOS(NOMBRE,PATENTE,FECHA_CAD,INGREDIENTE_ACT,MARCA)VALUES('LEXOTIROXINA','3','12-10-2026','BELLADONATO SODICO','BAYER')
INTO MEDICAMENTOS(NOMBRE,PATENTE,FECHA_CAD,INGREDIENTE_ACT,MARCA)VALUES('RAMIPRIL','4','25-03-2024','BENZONATO DE METILENO','BAYER')
INTO MEDICAMENTOS(NOMBRE,PATENTE,FECHA_CAD,INGREDIENTE_ACT,MARCA)VALUES('PARACETAMOL','5','10-12-2025','PARACETAMOL','BAYER')
SELECT * FROM DUAL;
SELECT * FROM MEDICAMENTOS;

INSERT ALL
INTO PACIENTES(NOMBRE,APLL_PA,APLL_MA,CURP,FECHA_NAC,NSS,SEXO,TIPO_SANGRE)VALUES('DIANA','LOPEZ','PEREZ','DLRP930506MDFYCC00','20-04-1992','123456789','F','O+')
INTO PACIENTES(NOMBRE,APLL_PA,APLL_MA,CURP,FECHA_NAC,NSS,SEXO,TIPO_SANGRE)VALUES('MARCOS','REYES','CARPINTEIRO','MARC56984HSCYSS02','13-12-1996','5698254636','M','O-')
INTO PACIENTES(NOMBRE,APLL_PA,APLL_MA,CURP,FECHA_NAC,NSS,SEXO,TIPO_SANGRE)VALUES('JUAN','ANTONIO','ESTEVEZ','JAES980305MKIYCC05','09-08-1990','0123648789','M','O+')
INTO PACIENTES(NOMBRE,APLL_PA,APLL_MA,CURP,FECHA_NAC,NSS,SEXO,TIPO_SANGRE)VALUES('ALEXIS','MALDONADO','RAMIREZ','MRAR900311MMCJBR15','27-07-195','360852497','M','O-')
INTO PACIENTES(NOMBRE,APLL_PA,APLL_MA,CURP,FECHA_NAC,NSS,SEXO,TIPO_SANGRE)VALUES('ANTONIO','DOMINGUEZ','GUTIERREZ','ADGA911228MDFYCC02','28-12-1991','5678451203','M','O+')
SELECT * FROM DUAL;
SELECT * FROM PACIENTES;

INSERT ALL 
INTO DEPARTAMENTOS(DOCTOR_ID,DESCRIPCION,N_PERSONAL)VALUES(1,'QUIROFANO','12345678932')
INTO DEPARTAMENTOS(DOCTOR_ID,DESCRIPCION,N_PERSONAL)VALUES(2,'DEPARTAMENTO DE PEDIATRIA','65398465210')
INTO DEPARTAMENTOS(DOCTOR_ID,DESCRIPCION,N_PERSONAL)VALUES(3,'DEPARTAMENTO DE PSICOLOGIA','85462539754')
INTO DEPARTAMENTOS(DOCTOR_ID,DESCRIPCION,N_PERSONAL)VALUES(4,'DEPARTAMENTO DE CARDIOLOGIA','56981256432')
INTO DEPARTAMENTOS(DOCTOR_ID,DESCRIPCION,N_PERSONAL)VALUES(5,'DEPARTAMENTO DE DERMATOLOGIA','56982103205')
SELECT * FROM DUAL;
SELECT * FROM DEPARTAMENTOS;

INSERT ALL 
INTO PERSONAL(DEPARTAMENTO_ID,NOMBRE,FECHA_NAC,CARGO)VALUES(6,'RAMON','12-11-1989','ENFERMERO')
INTO PERSONAL(DEPARTAMENTO_ID,NOMBRE,FECHA_NAC,CARGO)VALUES(7,'ROSA','30-06-1985','ASISTENTE')
INTO PERSONAL(DEPARTAMENTO_ID,NOMBRE,FECHA_NAC,CARGO)VALUES(8,'ARELI','20-04-1992','ANESTESISTA')
INTO PERSONAL(DEPARTAMENTO_ID,NOMBRE,FECHA_NAC,CARGO)VALUES(9,'FERNANDO','15-02-1990','CAMILLERO')
INTO PERSONAL(DEPARTAMENTO_ID,NOMBRE,FECHA_NAC,CARGO)VALUES(10,'DAYANA','01-05-1993','ENFERMERA')
SELECT * FROM DUAL;

INSERT ALL
INTO CITAS_PROGRAMADAS(PACIENTE_ID,DEPARTAMENTO_ID,FECHA_CITA,STATUS,PESO,ALTURA)VALUES(1,6,'03-06-2024','S',65,1.60)
INTO CITAS_PROGRAMADAS(PACIENTE_ID,DEPARTAMENTO_ID,FECHA_CITA,STATUS,PESO,ALTURA)VALUES(2,7,'25-11-2023','P',82,1.73)
INTO CITAS_PROGRAMADAS(PACIENTE_ID,DEPARTAMENTO_ID,FECHA_CITA,STATUS,PESO,ALTURA)VALUES(3,8,'13-10-2023','S',63,1.68)
INTO CITAS_PROGRAMADAS(PACIENTE_ID,DEPARTAMENTO_ID,FECHA_CITA,STATUS,PESO,ALTURA)VALUES(4,9,'20-01-2024','P',71,1.76)
INTO CITAS_PROGRAMADAS(PACIENTE_ID,DEPARTAMENTO_ID,FECHA_CITA,STATUS,PESO,ALTURA)VALUES(5,10,'18-02-2024','S',78,1.71)
SELECT * FROM DUAL;
SELECT * FROM CITAS_PROGRAMADAS;    

INSERT ALL
INTO DIAGNOSTICO(DOCTOR_ID,PACIENTE_ID,FECHA,DETALLE)VALUES(1,1,'25-11-2023','PACIENTE CON URGENCIA DE CIRUGIA')
INTO DIAGNOSTICO(DOCTOR_ID,PACIENTE_ID,FECHA,DETALLE)VALUES(2,2,'03-05-2023','PACIENTE CON TOS LIGERA Y GRIPE')
INTO DIAGNOSTICO(DOCTOR_ID,PACIENTE_ID,FECHA,DETALLE)VALUES(3,3,'19-02-2023','PACIENTE CON PROBLEMA PSICOLOGICO')
INTO DIAGNOSTICO(DOCTOR_ID,PACIENTE_ID,FECHA,DETALLE)VALUES(4,4,'06-03-2023','PACIENTE CON PROBLEMA EN EL CORAZON')
INTO DIAGNOSTICO(DOCTOR_ID,PACIENTE_ID,FECHA,DETALLE)VALUES(5,5,'13-09-2023','PACIENTE CON QUEMADURAS DE 3ER GRADO')
SELECT * FROM DUAL;

INSERT ALL
INTO RECETA(DIAGNOSTICO_ID,STATUS)VALUES(1,'SURTIDA')
INTO RECETA(DIAGNOSTICO_ID,STATUS)VALUES(2,'PENDIENTE')
INTO RECETA(DIAGNOSTICO_ID,STATUS)VALUES(3,'PENDIENTE')
INTO RECETA(DIAGNOSTICO_ID,STATUS)VALUES(4,'SURTIDA')
INTO RECETA(DIAGNOSTICO_ID,STATUS)VALUES(5,'PENDIENTE')
SELECT * FROM DUAL;

INSERT ALL 
INTO DETALLES_RECETA(RECETA_ID,MEDICAMENTO_ID,DOSIS)VALUES(1,1,'TOMAR UNA POR LA MAÑANA POR3 SEMANAS')
INTO DETALLES_RECETA(RECETA_ID,MEDICAMENTO_ID,DOSIS)VALUES(2,2,'UNA INYECCION DIARIA DURANTE 2 SEMANAS')
INTO DETALLES_RECETA(RECETA_ID,MEDICAMENTO_ID,DOSIS)VALUES(3,3,'TOMAR UNA DIARIA DURANTE UN MES')
INTO DETALLES_RECETA(RECETA_ID,MEDICAMENTO_ID,DOSIS)VALUES(4,4,'TOMAR UNA PASTILLA CADA 8 HORAS DURANTE 3 SEMANAS')
INTO DETALLES_RECETA(RECETA_ID,MEDICAMENTO_ID,DOSIS)VALUES(5,5,'UNA INYECCION DIARIA DURANTE 3 SEMANAS')
SELECT * FROM DUAL;

SELECT * FROM PACIENTES;
SELECT * FROM MEDICAMENTOS;
SELECT * FROM DOCTORES;
SELECT * FROM PERSONAL;
SELECT * FROM DEPARTAMENTOS;
SELECT * FROM CITAS_PROGRAMADAS;
SELECT * FROM DIAGNOSTICO;
SELECT * FROM RECETA;
SELECT * FROM DETALLES_RECETA;









